---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgAbeRXtv+cP/opx7GwbSAYE0OS5xGK5Zkk4SO2FaHtlfmNc3vvUspjm6FltIUSNIxlSNiTBHSkgHXUbxCgxxxTjfnQQcFzff3ysXMmfrmHi/qTCLbPSuYJqheD2K9L4ZHH8D7yliv55rb2R/DOB46U78ZJKOBN5IP1h5cwZm1TFy/NvNRupAIDui1AG8y68InRtd0BCKkE2qRAKRM8xVppTq1Q9w77hpmRqrusEZWoxVIr1ZZIL7g1HjvA7L2qcHmvCIb/kbY7NGnSl1RXAurKMg3HJp5jy1p2kfoP4E3W6PdAqvx1p1K/KFygAOQ9Oe4j9e4l1jagBJ4WxEaKLKle/nITZwhQyb8oKaF+bML+HbyTEeZ9UpKZsYohGbi7qHFtM/ClMSorwqbMlSvMrMuah79v8g95OlSQUTZ79KjmYEb0QLjzix0+rjHVJm5E5ZiDmK4d0fqBAm/FyG1ZFfHtkwCnj1t9EBnJ/Ft1FmyswuVtxw0iVAFEy0yZqaNu4w/F0vnb37Yvcz2EdxZPhcan6vzvt+lZ50u62TEPu/SaG4U276ZacgZqBnd4fpM8yS785bL6GVYfs1slJvsBcSf3XnhEfNdx3cAmiVoE3okUJFetHrP6LikopVAC0PgHos+0RMaKsaL420Jlo7/Ckc7vLE83Sp7Lq9kKaVvMMYHdp01d6j+IDn/awuh3UbaevnIiGqf+2jMTlMecg0OKuznE=
    admin-token: AgAq1YRO5JZehPqAxHzJgXE6VDj6xyqyu84hBvgZGZi1WxlSg9+jm80A+qjmeX1BvnI7TXRUBGJf4yw7eJ3c0iO5RUT8InWaEoRfGutLR21APyKNLtdV6N9kVcvliDkgbyTKjIlFhCBAZbxTLA5XuQNg8/jJUfqoUaW5sAG4XJuipPi3N/mNGbh6HiWyRyGOlrupxc/u6IX4Xibvk5VhAm8NaGC6peegbtN6QebopJVRQGrSWNcLLnBEX+2RMM8pSyVHFm/5X8VUOaWridzZn9pPPG4W2pVQt2nFduKNJrE4MlVD6Ps45PPEdHcYlkRf7wPaUIiBSUUSfXjGb73WSOs1cLjsUXyAHdzwax+pgTiYwQb5reRqr4OPZnRn68VEF+mJgRSt76hw2z+dT04tXWJYmeX1a/ABQwYwhRGJYjJYqjssCVnvw3SN2BxXoPzTWxYU/qIr9qx7aaEtsi7jgMRlkjEVfov8jY5i5LcUiTQddQIxDAk7Cb/GFEw2s5048tTmppD1LOccSDsTnPK6Yi48IauWas1rmTt1cVIPgj4V16kW8rnk6Gcea4Nqx6hJr6BI/BbZt3UVSPmulRtUzho5Jg8tmQDQbLAflYe1OujsPvn87PmQ53vqfbdw2FChXMKvghhpgdn1osqe8VUec5T5DARbjNsL09Azo2gxngONx3PrHZUbEgMJsDOduOnznpZhu/tokiQuJlihfGcf3uvzBOkEqmkTHCJ+WUAHAmqXIHnp12jPyl+Unz98Ge2MXf46vr1fR/Cp53BpegSpBtap
  template:
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb
