---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-db-secret
  namespace: immich
spec:
  encryptedData:
    password: AgCM68bQ5Kw+gaYQcOrclOw6j3nue5JIlYwfrU6MUWKzexp0kHa44XKC8JtqZAFkBHwC44B3jabs+vbesIOjfn6SK2Wr6PmwMiZV064yGTnzhFpGmWD+HxLe8h9rEFSv8TjVvWDaipNzQpOZsnUWO1Ysksg3xEs5l5tZIz2+O/EVBK6/3wFJsSMjcwR2ETwB31D6d5FtVztZGtbQn9XQT10DnkIVMbuQ1Hj3y+QX7554a9+VHG2nbBXSnn5QUV1pEJKHDGqgtJh5tml6bSZmkE6sSdrvkt8ufDBClwp0k6o1MfNVGKpddo2qVwJV02/GLZdAZfvJNRHTyK8S7VVfnLPRbJV8ucN0ayFix3cIUebAi2sXz60Xh4e0CAaB6os1iSHyWCF4SvXvrfp61gkJoVXpq+RUcG1ha5qhXQvayNbcxp837bj7gXnqiGRiTigY85daKaTS3FSSU1gPRFQ+IHORG9URtAIy+di2fF7fzBBszS2F1cHn1wdb18hyTIZTWUOzi2Ac31UXz+O5WKzGfwGU//2M8AqS8pRXQQXMbL2dSSdyt01Ms02SMrjMl/mwV3yjVKG3xlSDxWIQUfKISPI8V+HUf+OZUgUJBL2uNSMpVTij2vvWJpsqIp17W3CtGP2JvPz5xLAX23g3hhYTPMKQ9kSV1PPwdGSuKocYxXx/w93yEBp9wk7YJyZpC+c7Nbb864+HaQoHPFN4ew==
    username: AgDHY1lFRVEO8vd4JAdcBRTJb/FhoQXXniKZx/7k6QJMtnu4vHWOiTinyT4RySuYBW+CiENXeklz2b48JOGj+vIWp/CiycLqcZP4hafbFD4nvqui1+C5xIY4irvQlHgPkkMZC+5CIiVuZd86+i3HYvcYAAxRYeAVbh+EBGeoXpbqRIrHOXio85FS8nDOjPHX2MZP2xXf9nfM1iMCvAtEyTopXeVmk/h2nTI2hBxeYGJ2jWqkJr11YHsgOkkIjKLImMi5yf7V2xAK0NteWPFSFg8mH7ThAljkSq0GCbAOTCQwkQnGzmgQUwwJOUXCuMxt7THiNSW6M7ngK5mdlSVOFb8oa0WBhSl7ffx1tLChMXzh/6ib/k63eKk8y0HxUt3eBiwCQtn5ldBxGjWoqGaT1fx69fdGDmAtnfIquV3wKdWsL0s8eSMAYj4Xl09pDTohl6MivRq/fy2y93z/r5hahfxNd+b9d/9Ie6O8nrBw3sbHQ7wJXjE5MGA69dJzeVTrUyue8T9A3WTGhajEVSp717GVwnDSeef+Tmxnguzfz0aJgRyD1lehCRoma8DLhphWqIVpCFyfZoPFwTSx45XJvzFT3PVA7eaLgJgbLSn6fQHgPI4dHqWU/KjyTivLE4a2ZQs4HPLGJCywRmwPS7TffS5dumt2PhrpExNL67/p4x2bjZZ8N0jmf9HOGqA+wli9MNVeYjoFiDQ=
  template:
    metadata:
      creationTimestamp: null
      name: immich-db-secret
      namespace: immich
