---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: freellmapi-secret
  namespace: open-webui
spec:
  encryptedData:
    api-key: AgCUUMlyJ2BN4xwe5GQCw3nQ8Lt4wNnz9nkyiLqPmwrr9Gc8gZDYdS5RVm2p44E89IWU/z9v/+a2rIligsJV8JWfsinZQfAR3pIXh6k08r5C4SkeT2UgET4s940wZv9teo7OS7qhgX6e1kFdC0dKK/ITMLmkISZZdVszn6rTUabpB9XgQ2jwakmIV+iOjK6v+uWQ+kw2TRm5V7rdFiAQzsw62epnzT0XnMKxdZAjtp4C1IoAapx6QMfEL6UQ2kMiTWuTcthJ3/a25Drg3L0o03onnz9ZjBYH1GC9ItDN9z1iU0CzBICmlY/qm+2FUWFf8IIun8GFb9g55VGqCVMH7BBuoDoFphNf6ctlEyt7igGHbRdxS+hASx2o1AB4x89GIk3LyI1TBqYsSZ+jcZK3osL6H2vg6O2Z34oMRxubbgQxQfW+gTA9GuTtp0gUpRBB6XKiYBg2irReG7gAFrvFqYgL+lm/zu3KJG0vGOxwQEdYZVGwEuoNx+92Sq8ThNraklMJ6t1ry19tlRVT4gQ8wdGjbw83HsxzMLWTBYGq4sFlQcwjcLrQLhXvqdbbAJ0ldiDxvan/x/2sVjVG6RY0ieAr1xFltNN63YvPlQKnylsHKJsR1hTjcj8ylxReR1PHSxn45Fjxpvv0OgnfxTV1uYdgaZBYv1PkLKnOwKeOObv/pHZgeVetokaHH38nsf6S0nvHxVyQ9Twp+lb77OGjQjrWsRca0w0ANgQpFwb7AFT5lrZYsx16eNl0QrwwFAeZYzE21coK54MKuMKqPQ==
    api-keys: AgAHyR9bwUpxb1i63WL5y4C+p1fyDt+jKMm0lJdVWpnJ2/PLnXT2lQ1dmogHiLRVo/zkKGy/OgqRGH4AWvHxNP0aOQE3XaFWlEHrn0fVBRIDRUiOmTZFRrirAW94N+gmi9JK7Atq9JknZ0KeKowrZUzo2Ns2p8WbSU330kEyLOKDjhe3g7FzFK1D/Hn/utGSNcdOsmzLelhL6OCdZxYlfLK+Qljtz5YRbeCvfAaNeBbbgRBHAM3R20t+rnEWRgGuKA4hd0yW2jJvUX0gm+toLd+52obTiIzn2UmPz8R9GRcvvwxMS/NmTmWf/AEwlnb6Pc4dv4uMhvRQAIXqJQ9FJdTPknfhRt4/lVQczPmw0LGDeLiDK4Bi6tIHnp/AoZlkUzYfoH9fTW6RdIQTvwqK9GNmFqGv5Zr9TPdzDfF6bqqVTKbgzGGfyaLUOlyZu+criwRKwa+bG+w0PwRxLThFI0t/eyhRIe6TLhjWBBsIZUv1R8R7hcz5pR+UZOt6iGx6jkjUFGFb2mW1mrtLzZkTBa48oQTq+MZx6M9kj9wA4hBgauY6SAn4gBpd53P7sV3A/SY/6lq3qD8YXeoHVYk5NCNf7NgaM/AL/OY8rEp7XGjXkEpiKIKBDb7TEuCz6kqoGXO9CCKNlQqGPIuz43RJId9tXS4+1I1718LDRJZIZG42/f/qYaE3e3UCgybrxMc8xP/CKwBzR7R3ZEFvo2XCupSlnMaImoWIQX7cQ8JNsljGhqydCtVWiDWjxtRidfniPQs1sGAJGFzpXe5vvKgNyDPfhyR5fpf51DbnBJ3HjL9RoX4xKZcDPwbvvM4Br4T6api+LjREhbE7ocOa6BnTsc3+ITd5yWNvA+s4QTpM
  template:
    metadata:
      creationTimestamp: null
      name: freellmapi-secret
      namespace: open-webui
    type: Opaque
