---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openai-api-key
  namespace: open-webui
spec:
  encryptedData:
    api-key: AgB/dZnUf79oeo2P5vexD0F78wI3UnjlebrDODK4us69SEKo0y7VzdUbuzPnHO54/EgNe3xDsFgH8lF9qzFGlyCGBswEMQHhgrnQ67PUkYqbnDQ3qzlYqAhNaGPYtE0Z05qZSxzU6nJs/lX8gfVUKDjTtxjhpZ3d8p33rNwl+k5gkUuffLZdXLer8SYs/EdegyfOrKVEDBlth++mke1QxjkH5PPTg5VbcZr1OlOWD7bGUZ6SNZRa+md5LJUeinGclG1kuGMy/t8mx1AwoCb12RwdK9lbCN09tFD6EJtOQxrMJLMsoF+wwQzRkw2w7IC+u4/S6Aha2K9bCSRbbujtf94Bti/om5wtN1u7uj61RhbXPT1Yl3a3iCoox3j7SXBh4r3jgy9vnRV6eD6BmDFiHQIA4zMY1ObNAhttjNwNT0iC7Z/tJ5DKw+Mxd4K9nXDqTwBnv1ckUao74l6w7ghPwK0EwvjITXNUWgRyS0ixeX28KURHWUujv5+u5/tTxTUKNRyaLceM0yLnyamI8s1wlvR2uyTHZp/Vq/qpVb1+jgeVFjwvwKiT3dNkjYqq+af5wpaZJZ0GKds4LLK6HPOcOY8MN7k7A0S6pG9lk+QRzjk5+FX8Ajm1+Nc3/AI22rZdaCXkG5f2f1X4YwMiMi/Zkr/e+B1gD++8oijdoPsG+avR3fSncjrvWPoBgGU+np5v7e7WUnC7TQySZ6OYOORKmHizFu5lr/UsIGW5j24pN2BqktMKaq9porm3RI/129QWpg1tQ8JF8MSG87NCxQ/Yfqrb
  template:
    metadata:
      name: openai-api-key
      namespace: open-webui
    type: Opaque
