apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ddns
  - flux-system
  - immich
  - influxdb
  - infra
  - kube-prometheus-stack
  - loki
  - minecraft
  - sealed-secrets
  - zepp
  - holmesgpt
