apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared
  - flux-system
  - health
  - immich
  - infra
  - kube-prometheus-stack
  - loki
  - sealed-secrets
  - holmesgpt
