---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcpo-github-secrets
  namespace: mcp-github
spec:
  encryptedData:
    github-token: AgAV35nuUuf1qoF6OLiVTORs/gpYvt3N3IiQQh2aoRSxJXXqaguriJBDLn7CrV71css9U7oZV/4ugS9fQRrL3mFZkRp94wmq3amktvNmEyBrWGBVNe4CH2IKa47PLaSDU9wCDR0hlxWiHf1fh7+lO+EattF+fpSwMnzqV6CsGErWESfxqjB6+5aWunvAPzPEorRXZWMEjlTq5+FREm3UzhUrSvGR/OaDqCXl7+w6PjhBw89uU+7cUERwrTXAOtVBOpGfUv/gCRoT2CFal1ZjbsEJGauRzOZVMTvk7tW0zfiazZRIm33bKu28YxzxRkqgRHu+Ff4LvSVDxKxWPQZJYrZYEWLjdEy3iu5Cr11FwJfsa64+t07ipEiksQTYAYxW5YtSCUJImlqZlKgg4/R3kRc270PZbn19n/1Q/iZA0TnP1hD290zX634BtJjMPSyw5EO+0DsDRXiODiNc/7H8lT0cpG6odFpajasu0zaehyQ2zlOzLWd/BgsmGIUxThhxI75yV/o5HlnlxJ1Aine1s2SsqWokrG71+FK54HtuYm3b6uo2gZ/sxSS800jDhh97ePQMUjBa0mCtbHqv7jFUIDxhqCfNfndzvsLcveeOQhur+6uyFjdkUzp33m4ZZeX3lxkvE1ZqxrLjM7LDEc/6ur8Cdt6/70k5plbBkKfvvgceL3ake0pCpjPNt1wUKY565Ely0m4chYyQsPfJeG/gqhPL9ga77DCgSndofGhPsLIiYCXJWeWiCxGk
    mcpo-api-key: AgAF9/cqVZLJUMmLe7x6lHfETdYfOPH+Jl+uWiFejVQQRNOBBpO+eRn/NGRorW46zqdFMY8NLZrSS9eT/FEEXUAj7Tj5smE4KfXvtlRX5C4cA5rEIDfkYdGpwkz8UjCo8fs9LaBR0CdUroqDU9bdSqLnG9hLLGdgRRq1vl9dIHMLPG2CYYa0zjtiTSausDrzXD5JX8EoxXpnBRWfWKNzH4mlt5K3Dij32mQwqtQq2mk3OV9uhWuxUZA2XEMs2Gm70pJd48V2AzqyEqVa5oFXJFp+CX2cj9gjHulsDtrTtOKMgbAzaFvxbhDJkXJLAquRo9qL3UhNu8vpKzJje+vk9n+FWqDXksdhH8KWjDk6XKAcAsQo0d+eqktKpn56iCJCe2OZUbCFiCN+z4D3sMKSPuZpW3Ntq0b6zSDOy3tFTu5kA18nDQRT7HLrjcpQQp5BL+R/5JuG/siroOv2GcuPTc0pqc8L2Ah4ZY2F0qLdthuQfmjeRDiml3WMirlNogLd6EIiOcEz/4n2bO3iGoAjgeaJILRP4AXbizXYG69/B79lcjtDH3/osaAwqryNDxvp3keoziANSeF1rcHpJpHdAZsuZeZx8IwfM6JjqU9NXcI6Q1JEuD7niMP9esGofcW5gMrzZmk3pjLQ92RC9ww9UEm5M2504mHR3tJ7HvxonuOU9oE3DyJesM7zxLSwXy+XaruXUfdBHEEI8x+DTBLQS7krvADrUqNVcSouCO9d9m9G190t9gTVOUvTylaewXnT8fE=
  template:
    metadata:
      name: mcpo-github-secrets
      namespace: mcp-github
    type: Opaque
