---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: holmesgpt
spec:
  encryptedData:
    .dockerconfigjson: AgBVtOkWtsSwEHWvWw5AetYbZ4xc8SB/jEBHmwsXw1epZtPD+hSFK0SuTBuaJpShjVRNc/3N2Z0h9Vgp45fB2ZuVON7ywz6jopqZLGLauJpcyrnzgN5UlFj9WLG6jhIKJfmkr/h5NkPakxlZY2VZvIXYdyMQHk/CTUqRidPJpTXyQZ+AadhsfhgU3bnuD9xQswHzg7y4RQRrpaKh1j/0R5QyPd6VvdAurnFja6VzZzXS/MkqRsYg0waVdnMFlhmxxdefyUJ/UCkf4nEvqSaeGb/FKzojCXRFr50nAL2ZtacujOoqyvmnnV8v76t8eL+re22aQRZkUcgY1Twcl/pLfNrFqlcHTNAj8Mn+i2z6oF3q7x+zzDI9vc0wY7kJng8LErUmvPy8GvHgK5MEpyfkTf+4weYMpxChHtTfthM8JvhprigPoia6XZmKisHg+50CUbJQv9q3fh8jq/3n9aSDiimIj+djW7jZ4f/WiWY4E93VdFlleRwwQHrZupxP9xXAY/64Tb9qbWR76JP4G6uY+HqDhyIKzLE6mX8PoacaH+dL1dCTnFrvVNcdBH12pb0AF/2CGEdPh4lEbjBT1+ABiamHykJ9nUiluf2M8mVzlMn6GWtTX6Sebbb6uHZzJ0wTPHh2xpVRZOQc97xSefNxOmXlbEpKZRY+FoizJIUYS+HB3JnonThQtmN8zCDPIRJyh5XAcMl9jCA+mi6p+QnWlP6z8bHXxOgEu6DQrr5J7CpfzLYe62fIPPUboxbaLOwITNpJVEsdSP4RvK4uMOI8nty3s0H86eOiWBV4EHTnL1S57K8pKN25JHwkj6kRkA0A69A6udDXE+TrWyxf8aN1cWbKiJk40NpPYvDefk04tfxNsdN8N0BmvTegyrpAPKJPjtSwrnrxxmHWQ2shkqVrsQ9KW8up/2PvnipS4hXwbCP8eLchKnoOPZyoeidROubUPkMfqpZpvXknuSycBfmwUctZag==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: holmesgpt
    type: kubernetes.io/dockerconfigjson
