---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bridge-discord-secret
  namespace: holmesgpt
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAPa9rBHqEWKfM2Cj9mBUw0YJYm5G9fEbti0f6XOftInOS0LVw8ugnoaLfV2JuQUzr+w21B3JItig2LZcU3/Iwdc9C/4gUVqK764BBzjbWTTxE0bsNfxzyZbGG14t1XVjdGXk3tJdTq4uQiVgikw3PfIB6x0gPiBsZVcDakaPfrSJsrn1pEW1mNGmkpp+MtzQVmsEgyC1q3LoBw0yOpcUvw9tT6b19b+RghT5PIhMemknSIjlTmqQ35nnJ0O0OK8utdSXuIFupZn14w2zljFYZZP009kWvMy8s3qMeE4MJjdfyUZkzJS4eyKHGOhfB3/Fx5JEzlBTZ+TyXpFees3nB1lO95EtO09Ai+6v5M+VJRa1CjjeHwFdac5F7dxbr+GZGtQzOf6dDdBPGglM69YMiPxSlYiAQyCN6HIrFBvxCPRxKprR6BuX9ScvWZD7iQuXUgR8KEdnFsUhYMnHTH+G5UDz42Wzmi2vGzdk3PV0+fprtol+QtXrQeKd1hIiOZB/D7B5Y/HM/PWNm4bpIpRm7QOXSxWU1UxuWFy7646pZNeeM3XnbIcHApMKD4A5h+27r5dxUUBJBpTWmmK5NnlNMckcjtlA83tHkgvj3/OfOuMZrx2NXz3sZsv3yoQYPORjfm6WWTvhP+UQbRuxwWGyEPcVXx8tUtvUJ7JhJZZR13xUe3T2jloB6gR99pt9g6r1Hkli8CWpRUEnTGZ6OTcHKGkOebbM3x3ugGLdWF0Ph6KLlqnKOLYi7KAZ4mTjA6qZcoINgirBmYGOz1DWA/oWr5OkoBxAs+eX8oKDCk8l4h+OBK1c1QZ4Xo0+/fSLbBcZ/j3NB2nwidXOF6iiEaTjO0UcUp4xKVl7nG
  template:
    metadata:
      creationTimestamp: null
      name: bridge-discord-secret
      namespace: holmesgpt
