---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bridge-discord-bot-secret
  namespace: holmesgpt
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgBlKsZZonNV6Zj4dg2E/f6u7nidCmZYDAblTdSeZcggS3dMM16oufmQ7pTXDNFyyl7xeuWLuXX2QfaU6JhwIZSBOUu4OZWmYCd/f4QbP9h7uHXQTJuwYgQMk0LXSdXQK25P+jnKDMPaaUkSuHBvTPF3QyzVO/+0dMI/AaPBMv+SFdA/IQVTv4OW52GpCLpaSccih8oXd6xSHRUlHcB039wdKyyF3JQb5MD/lS+JHMeH5uwwcf9yneOq5AcRHM0KGpR6/prWXynPkxcsY+Hy3te3JFGfDU2bEGjo0qFHvrY5AZvZ+Qr8KzUXTewsiGxTsOSD23WeqTfJYhz+7lhUrxiy2Hgg9Y+q7M+OdqGYHThYzj4GoUPcwBIKlpht9DRobF5M3HvElabs15P8ZVp5Y7eDlH01JwFJR8uHdvhgupjQXxYf0VBult4JqJYT9nlAuPpPspzGocCrK1JRlJFBGzSld0MIS399AlAiKO0Y6Z6OcypifvR3UXSSZKySS+UiB31eFCTQxRstjrX018TK3Q+ZgADsRRa8Lw8812iKYREwXLoBMbcA13rZ9UTt07xEQWSzCtBUH4HXghkEqIadZpu8+OSHDtE6eTf1wEmGIUpo8ZO+buqPtARIUCb6ntnsgJ4mOkhBZ+Jv81CD8Z/7NB1qW3nL2vqchTB4x5pH50wB6NOSxvmL/sLaLHN6UVyXkMuX5r9Yg3UPL6rNZbdjbUooYoM4dJ5b8maz83W+s6xwxQsWsIQ4/qweXN2uEtPASnbFY6Am7i9hbBS5i9WfuZKBDEWlHzm0TEE=
    DISCORD_CHANNEL_ID: AgCANqbs68h0HvJgkMltQ77OOYeHCxbqf2g6TJ+fCQFuF7lTC8UxAc9bFUeqxfw7AasB0rxnEa8moc3l1IV+s9reOjJ5KZKzM5Xn8lTHcJZ/WGKv0vbYK9CtuSjeT1S+r2o+DNlifcYdUIz8y/jXWqiYJ2eZliiR22CcqjIS+Ls87y9DOA7ah1EBoXQ/EjN2TYzdaZVwJgyafarMOLEXZja+hKaxvxpSv+MLxdSUREXKHS1gW0SmvmvkQTvlOBLk87Wxu1rRwmNGMPe5cQ6CDtLHHydkCAuXHEMoLAsRLxx2O7BcMXWl49nbBYrga4ZmSFBnurt0Xpzg//fli4TtnCPBcNv7E9B+7OTIdUUP2B7BL/6M4fqUgSEkj0VwkMRnNCInJ7+XBe/1vSLtMus2mFhprhpngRsqL4p2yrbas9O1i96/tyEvRB1bJ/M/nOSegqt4aN21xLN0/G6JtcAI6nWCMVAjVswisvtZgX2QwYJsV40E2IXX8jBUB/xHnkEAD9CoThuE7w57APglrWUNRbYUCfrMMZrItcCNQtJmVNMrxyyFOklwQ3P9o7xObKUojl/j9dvCyn0LpFWkYQJJwntwmW9GrB9pYuCDV9kbTGBeCKbGBzcrMzGD331dh8IMJejdi2dRAhgQH9Ud4Rupc2+s81ZQ1dxIUtgt3hV0Z8pOPdkX5BYTkototAFsQqsLvgx6LZIe4+bqNC4SJAHz0Os3X4qi
  template:
    metadata:
      creationTimestamp: null
      name: bridge-discord-bot-secret
      namespace: holmesgpt
