---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: holmesgpt-secrets
  namespace: holmesgpt
spec:
  encryptedData:
    openai-api-key: AgB3yU3jQJHG79RbV8Bb0LNWZhuYNd57Ufb1+7fK9tzXu5TYIjvxSQl0iwScUFxJe7Il9qYtvvFy4WcqFQ30wR4BhdyTts9ai4qLVUCYyIPtE710kpFprH9dbNBKhHG1aEhpbnLsrsB09cGWF1fip5iCEWJoixzBsrPrOoeb1gcCM5QLvrAUlYpuVwj4fN4AvgYpimREL4LDByN2SwOs4PJXQSdslwlI/G9OhnZidbLrjPdb1oExnbZcqnwjgZNJLRm/lqvHG1JcMDz775NA6ysA3maWJ8Oqo2aQF0IpdClCqp3CYvPgjQ9gNTaWAnnsGiYXU537Id4a2vb2r4SmdRcpcmPwU8Ra3gqD1J5G75oGn/i1KDflApDbXrQHJsQ/E6lwN/Z1sYtQ2ewib9dZou0+SaE4oWQunyuMJih9grD83ckWzobueJ5+R/e3UswxoKS0vYsXFvp3Hyo5JeDmXAs4Z9nLF9sYH8viG2n2Wp7bASr6rakKwjGUfkmlv2HY64OivLjyTH7lpI04WhxpeuBFAJXVzRsyszG+HwlS0ljS9dAC+968riaK+xgSIq33tCSEGL/OgZPhSD810aKYtGziPqUykoXizMro4mlt3acpqPU6oZo2dyuRp8AWDS/teULQMhGbCcoqXsC2/pn8DCb35P8YVc5te9h17DyYmblr1pPf7XmgegpHo0gtO1FMM/zDH/XEZtMaoyiHhHotGy1SgMkKjYGmYbfvWX+c0VnV13gWhWopujlgHg1yEvO1bksc8IUWM3L7uG+RgpLkNkIE
  template:
    metadata:
      creationTimestamp: null
      name: holmesgpt-secrets
      namespace: holmesgpt
