apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - holmesgpt-secrets-sealed.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - bridge-ghcr-pull-secret-sealed.yaml
  - bridge-discord-secret-sealed.yaml
  - bridge-discord-bot-secret-sealed.yaml
  - bridge-deployment.yaml
  - holmesgpt-admin-clusterrolebinding.yaml
