---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1m0s
  provider: generic
  ref:
    semver: '>=0.1.0'
  url: oci://ghcr.io/immich-app/immich-charts/immich
