---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: freellmapi-env
  namespace: freellmapi
spec:
  encryptedData:
    encryption-key: AgDI3twdNWNuTde46SxhYs4RW0Wg/Mpy1Ji8T7qjSlpUQD9FYXkk1NFI5baxNa6npXQdzXuysz/PIhjgqckOef2hljc9wAZJXA08+znDe44aSi+5Uw1ySENFLURW9SwRSkityoFEUB43rsAZLVkOxaINYIc7szLSRCVHvrDPKBjfTpev5nZD1RcXW+I1T5W7wEHGOckXPzup3RphmVCZKW2hpM1GVr7JUHmofc78ouw/LT8r6ygVGBYPwUdKVdPRVKi/k+W8wF0M9lqQ6oqC+D0k9nOn8uiiSxtUiwp+qmV99FHz8hm3AvUFpiDvroDg9nX9vOLMvhByOQdLVGNY0ItuZPMDDbNiW6SsDMFXENgdDkw/DCi6EQqW016g7ew5433TkQoAyuN8f+3Hmu+qUzRqnkq+nLD4O9eaK/g0jveL5RadJPpS0lQFVpUKLiPGZT6gCKowI11yPqK9KhIdoEttG1DZo61nnQp8UWr2O/05Xut3nPLKZtR5YWbB+GUetk4amIDVO33zuNMQfTT/UwzLpo12r3gzES34OoP+unQvkYzIFGC35H9fLg0VDNy4PBi5W4metsdcJZZwV5qxem2A32QHKPJt4Mlpp4B8imZD7EddWywUoEx56/RBPKGfbpQqJ7tRB2aJ7HAhxctRBFVBFkTk5ULJlXrG1xlvJC0dpULVA+WVxIcRcFZlU/pQW8NQbNSLPayNbrWAw9heyboSudcUHbzoxaRCQ71dwMKvHdDB7YVvr3WCa4jb2B7VgKeDbE67mc+khKE3eMCVL+wQ
  template:
    metadata:
      creationTimestamp: null
      name: freellmapi-env
      namespace: freellmapi
    type: Opaque
