---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAMkQTDXf5KKkUEawMHhJQLtGM3oO2aodjoeZ+N8D7dUY04vHQjvSuT5XVlmK/MHv6efiCsy4L/ZoYaZBYmQCYPnSgkRwWEG5GMToAYtyxtsPLtLT41JOZ3bkuAvLph7It1om6vLfUR75gWNTcbtVZ2MwyCgZoWv8ciAZKU3bbTcs412eiDyOUTVXMteiDOXzKexcdppGnkTL9M3n6pN/eTGAcWmmH1G2Tz89S4/TV3kF7MJWBXFhOfm3RBKrbn2/J6BdpbCfoZ92eUTP5BwPJaxuPSW+dTfdYZNtTvJO3wqaMinyET3brM/FpEojnFJdbfXPW8AQCdaBRLlneG74lsBMRXc3GsCwEdCxKF87Wz4NMmJrUSk4LyYog+XPVAAUTv25LVmBQVaAksH8JMjMDWh8+UnhNqFWK9qRxDlu8PbOKcRIQp8EcKe0vRO4gUJ8pLA8d5MpdBliLlHt6ntD7PJcdByH7eigUyB3Bgcr4Lsl0KEWZ2vtDC9s/9gt1A3Uw4T82FONSsX/dA8n3+Ak9RAGIiTUG0TQP//BWPlsYbxP/OfAi2kZrzciS68VA98cux9xDCi7naQgGtB5XIvMok7dM/G0CMLka+IVJJpu98K3/mH+jsIJ1U4uUoyGP/iPt2oWCZdgk1TtByS4dD6vFAW9p4pu5b5/ZQHOo/inX+8N7APLPeN7gF7YDpNUmsh0GK00BQ79n0M9CQV6HNwgAizzumITjoQ9nNxWTSCRF73ECFOoR9fF2x8FkVa0tSGQl/qtYZFs89RIpO2TyA1QFp9M0Ex/GYoRjNTISq/g2D4rxvxxvkik+2OMs9FcJhdh+l7Ft+YF+UYYBHVvDXn3Zs4dA3liwShOhR
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook
      namespace: flux-system
