---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring-ns
spec:
  encryptedData:
    admin-password: AgBV1RsYmxZ9XrV8EsJZC8qcaENX3GXT7rX60MFfnmQqMOHXJ5ueeai2rYrd7i6cE0/MN0PEW3LCxtGGE5H6/1istKlQYse1keCaMBEf/z4uQMOhwNM/c/WjRnoUgqlF7a2hc09njg/ZsozgAwkKyw5/z5/CzOph13NyvYL6aeh2I9GDqh+kDmzWTXzdhNaEqYCglSzSFRQyh5rbiJ9uQeGwNk0TFRpXvkAMBqlnHCRVvfOqlEozJsj3QOwTl6V01wmrGLLcgC6D2QkdBFWe7xrAdSoBbTpnycQZOrV27Ea5YKU+9s4GvZ4uEKwj+yNs0mF1aG+mYspGvrLybvP+6GwVnqpU3WsA3mmO0DaQpxbWbv8T5HLrTnz2/76EFw5BDkB0DacZoahhRATBCqCSmYsHT0rCDHoVhloLsdHdCIYisjVR+Gyienh7sxpoR4ImY3E160cCXFdrQCVfoi2nNk/YoeFB0An56agawiZAknVhSp6p8Naa1pZSUwLAlTchM33hGkk4lm5R/V2m0KgVw11drm2YWPhR2isaoEB/H+5HPtCjaw8u7vHUkWeYx6zepiyUj5jrAVM7PhJNAYFveGuZeHzENXsTbC8AJr0KElGC7DAD+oNJJPK3slnxtWJ5L6gPR2Ng03voMAP93g7Tbe03w2/ez7rXs3z2+Ots0fOuGQIZFQEt3ciVnDjVqM+aDVjuuZo0PTts7lxfrO0=
    admin-user: AgC0Xpnjh0yvMjN0aAiv4wlFmE0+AuSJOyQlwT5XW8waaWi2OilmlPhbql1VMdgQU/E3Zg2pPlvnPPjX6fAglKiXn9/XKm3Zh8S2B/8xoocgkfY9pX4yiTTLkN/cUh1md4etb1e8zU3CuvwocTcmvrwL/j08E8V+n0X1qJX8hzisYB0RS++8+AVOaYwBWhwokzRuZ+3kyDVUieY7h7bubaP2eaz4TFtrq5sXiCAA8M0sBw1xQmi2asaLmhWLWrCNqZWr5G2opwGf4r2WcXJGnzYKjYIxKV4RamfhtNmMZVCbqTDHkWmK3cXerf5jLv2Bchn3wpPmQ9FNNVmaxs+dpyplaApH72y/zeBZZSa4Z4Y/dyOsgp2sEtSgEK+mIOb5vwc8D/N4wRXyqsGJjYXfRjuAZ+yUpdlRcNEnMwdnM16iM2eNJQLCEFTch47FxkkdAc6BDdHHlqfoFAjEtMu2SxgCj6V9+VPokV3/3aDrOd3fqDcZ64cQgB1Pufkrai7W90pwRj/PgLfQA8/4uhKAu2xFZgNzBWDeRl9HraaDpqVksp2GVbmpBA8twiSGUqoh08P+v9g6a2w85OBDhNFE/SU19aTRq8zhf5SpWJl3va81X9soNuDe3qGYlxM7yzVd+ShhrG9tPsw3ez35BJjz21la+lqrc4x3+Aj/3MWSJWuMh2dGLGsfK95DMZkrxdLBpmuhXbFwdw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring-ns
