---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-influxdb-secret
  namespace: monitoring-ns
spec:
  encryptedData:
    INFLUXDB_TOKEN: AgAaneMAhKtfOMQJMBjJstDF8RvJDPCvShCVxodyUQu/C07IeQN5yIy1HQTM7hpdCR1xdCVObGiAXdBMdnHaZ5T1DQ1ARBf2Dd/UNOn8Rh2eVJLUs1AGETRvyVPOp0kSr6v1aYdNUBZC/RbWiNpqM3igfH/Jiie4BZPK7PqqZcT/k3ghhxaVR/BqYyuoZybBO6lEMvU6MsbXjwNTTAZdsh37HUABCSzBEVGszdHI4R744EsOGq/KcGUcwld2HWGYaAfV3QSU2wRLnbQYTxQ+jJBxkOfkopY2IlPoDoR19tKx+jAEtu7yHZMf45c5ZszLFFwANnHUOS95KKnTb3hIcdGgqOJJKBmrM95QNElEQYhMjIsGqUTC3SStTfb/ZB1HmWbRIR6F+b6t5a+llguCFwjFcvcU0NB0f3Af6VzZMRX6DQrhyoOnS2VP07ULdd6dkKoYsBlbhkY5XBnKskS6+XE1jHnpZesDLztoP7F2lA3QtC39HF/SgXdQylvjEOftLtboklKAV/8s/MaJC9Ug6WHB4VOZBoc+Xwelq+mp3Utb1pKbvm3yl20OMmkLFNxoASKtXp3zFdqQR+tVYZLpvguqUZTxIxAl7Wr/df2EB1VTPf2ljcIrjPxJnmvYI4psjVUq2fgpGfLErF1oW7x7lHBH8WCp9DFwj/rNrx+4IP3g6uPlRijsTATYIS8XXQxVUuGSnAtcWBgKCCmp5kVx3MXGB6O/RGjTuaVE7iILOvef5+BYhOkEH7QX0IXHgjA38yT3BgsNuRmhT7skY/F+gSPZ
  template:
    metadata:
      creationTimestamp: null
      name: grafana-influxdb-secret
      namespace: monitoring-ns
