apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discord-webhook-sealedsecret.yaml
  - grafana-dashboard-health.yaml
  - grafana-sealed-secret.yaml
  - helmrelease.yaml
  - prometheusrule-custom.yaml
