apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgC1KINGL/kt8qu+81QjGdVIGe5WEsRgwdHetcuJseWS8yQm87NnFkE0ec4/uwH57o/2zvvUmn0PtPRNaMvThdwYLNR+xGr7dTJkEiyDjPvi5kygb+iZH7EVMJzXBCtrCW6PiaaQLMQcovoI9gjcgFNP4ekq/kV24KbpLLxKGmbNFaUJUXrF1jyQFzzisujN+9w5ZvbU7GC/GHuDWjwNcgGjfcxK1E1ickh5/0D2BsXxyaDVeXh1ZdpNtpnrRm6XzHgSjidxOfoDSSrsBc2yLZnNBonCB8nDvtwDwtf0+/dgfoEj/aB9xaiYTKFGSjkEINzrwHyuknD9kVgZkKd6UNCIrfGcFCSknzOKJjI74gfwGOktJQDwDkUQ7r1+40p1y4bL7WPT+qx+Kaz1gW3+9Zpe3XFpKOJ6ApZWkcJRjxwJcmzhD4Whv8lERgIHzVQBTCVcKg//yMXVU7Ih7wlEgWeGTDQNAnjFnrSXxwSw5Az0AyWHCq3i+aK9m705JrFmQTWp1lIc/kbqJaKS0C17V61A1qbPH/vIxVG9/9UnUTC47Jo66jnIX43KhRTgi3JqAw3ChBbGQRgaHzS28wtSJ5pIsi6z21LLbk+aL08WwU5GpNeBbrvc8gfrNHBg8p+GE+DoZ6GIzOCawQ3+9kk8P0y+NZf6aCtEwovRzUtWcQYUOJgXF98y+QbEEG4aEO9tewdMoFqBTWgaeoVqVBpd96srQeLKpcxXtih4tsZzrdPCg4X5Y8qaau/wk3PeDC6HYtTB5L/PSoaxaOOphD+0jQSeo7X4Kd46yGVj25okblC0ZPQDV6pkbPe8BvJjQ/g5l93REcksLzk+a4//4O+P4QvgEwypqbOMOvaXS0mxB8fh5nF+L3SQYyZypD8Ve9TuujOn/UZsLc01dNu396rQ+sJF03ZJDGdjoUvRnW9cl7GO
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
