---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcpo-kubernetes-secrets
  namespace: mcp-kubernetes
spec:
  encryptedData:
    mcpo-api-key: AgCuy0BS8vuIUOyuIed3sBXTJBM2dZnzbFWdIUV7+IaO5BKaHKGDtZYLtaneteAVxQ1Cp8l0CsoPAJMvTS8KeulvbOKjwwrCUyoTh4ktJPzmEfNklxFvV1eq3ie3bNQMJTw5xE5rd7MSNfnzcTNRGNnRh5ru0QJsOpf8BwZ7ZFCvOeBdluF9350JWb6VFfQ3+xOjCdOVZgJyfOJmZB2YOF0cQxu20x2/97aCnwTONl7S+4K2iftMRjuUI2erHO275pnjUqfTGm/3AcXjAIeOwEKl2/W9JInvja6v76DM5Nb64yiI5w13dl1y3fLKCX/BFlS7zO5iVtLE4AsOsyFG2au4Y1rapeElV6SG6WYSLB0EqiSMzw4I7K64JJTnujYgvAqvtqe0I69o06Ee3sXTQaZSApBH651nTFZDhKzt04x5i6DqI6SKXwryOacicHVIJxSAi8rKf4BYAomrA0tw+PZKVeOwE8EXndjMhrAQOnYhHISJuI8tlT+zTFcONi2zbaZItpITaCxDdvkxC7z1/GW5anMBn8B+3iXku2n8i77xeb5f7zxKptXcCWWm0fZMXqwpuWNQl8PTa53a2/ZU3Asi2n4MBXKkpAXj2R51S8L3TOJWQhV3xl1R/7nl22gelopvwDxo3GoviwWPWi56jgYgH3fJpLB5lHDe7r9PcW/8b9PpYSaavXnIwFwZ9DZpPPLs1zS9gbCHrUBbVoVy0plyb4TzLGqQSi7L9LlBAddP4eMNz/bpUL9sAC6SYhq/X5E=
  template:
    metadata:
      name: mcpo-kubernetes-secrets
      namespace: mcp-kubernetes
    type: Opaque
