apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ferriskey-pg
  namespace: ferriskey
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: ferriskey
      owner: ferriskey
