apiVersion: v1
kind: Namespace
metadata:
  name: ddns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noip-duc
  namespace: ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noip-duc
  template:
    metadata:
      labels:
        app: noip-duc
    spec:
      containers:
        - name: noip-duc
          image: ghcr.io/noipcom/noip-duc:latest
          env:
            - name: NOIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: noip-secret
                  key: username
            - name: NOIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noip-secret
                  key: password
            - name: NOIP_HOSTNAMES
              value: "yoyo.serveminecraft.net"
