---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: noip-secret
  namespace: ddns
spec:
  encryptedData:
    password: AgAodij4s3MsDxTbjYsVjpCt9h8PZUzCAx16DxSlsk/sfpUjCTmSCXHYKTJAXneXo+AYws7yQea9MkUSV/U1W2MVVXL6LC3Uy6wzaCHEO2IbZ7BaZsNNrmrgPBHDBZwaRBSiIfwCQxUIjYkurf7apyj7qqzzqW5ibChWAsn9vu44DZJPr5+FZrw/3DRPIhmwbNjV0c7fZbZjOLM0KMZBVIZopMi2snmn0kHHzB3H7CxaybBhJz2DNk64wcXJML5GHHa/eTMvhhu5ebySwFe+QTVi5L/f5RY+qtexZUYG5Bbnx2loOlW2STqWx/rpX+1ETwc1hWY59AuSS2c8AW/4ZVZ9ZgyU6lRE3f0bfSAHh/igXJma2aQ7EVs7vzlk2U0JeDPUDs7A/EvV23wR+LJsdXhpiPP8fhnYW7ymANdm5n119gci4Z67FxbWLaGjehZhRAbzDXotHfAEWpxPTOt3nZcivD8a9u4tChTBb8ZOlwt+UXFo4Aupx3HbZ2qmaXzKg0LFvYmm1zbwqlbzhFjhHXrKiKnDTFD0DVg1q3K9vVgwV3QPrYWTtX56IGV7oHbwT2HqvxGIHfhFFxvxuTuXd4sq35gCEtJidH0jKHpb60orIRHWR/KT/j8fMHk4EY48BOs3iJL4nMtvsUnTXscly7+ZL0TOWxi4HHQKNAUHDhg4140LWcTi0n5uaAhAPyeToomPZYZe8xZXAamNiXNafxk=
    username: AgCc5Mgj14tS1YeV4dhMjBSqTf5dRB89IovVqnjK/MaEbOhtducPylsf5KNrzGsxd5oTRI0AVlCJuxuaI60WYrNl5RQdCS+R5KnxSjLdrkIP3YxUuVXHvdiByf/AyRQoRetR8UKjrci3fPa20iqp4NvgY+YnFumlZcp4ufKbZJGSaFcnHYz93WKxlqverqrvWZJIuIp6V0jX1vX5b1LUxnJYdAI6C+aDs7wWfBGWzgLAHWGhGu5O6tn8zAILiOrzFun21/GJXdA8P1jYXmr39weHY0XsMpK4pa5yUd5pO9uwlz8ijxJqvGkkeKPDQLbkVAfgT9CbO43JXqIFkCMCdIfVMVt0U52K86CpcCOLI6i8NzFwOLGh6G+Rt4n43UqEZNy4aQXo3BtDbpCtdN1UyxehUJVP2IWE+Tf1sGy0FtgLuryX0c+cj0Lz6CoxEV6iHJsJ+4MvuUPycKv/MbmEhjvfHioju99KoTMad5YZpRr5I6MuC8s9l5MAT1sOb68jHbCB1O54daDrAwAVUDUXJpIgyyUtijossfuoj9meEltoSmEVec4e01nQ8IOSDdMYVo/5qJI5otGO4R9KfgkZoRBVqSEZaWQUUbq6g/zPmfMjEA4h9wh6fU2DKllwI60RerXldn/+835d62tLLDOymS6GYwvgKxR3CG7Z63eNNuFJWsYoz9rGzXUEwcXNZ4SUnnvi9/TyKUaD18Jq5oxsfeT1vEbHM0Y=
  template:
    metadata:
      creationTimestamp: null
      name: noip-secret
      namespace: ddns
