apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: influxdata
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.influxdata.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  interval: 1h
  chart:
    spec:
      chart: influxdb2
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    fullnameOverride: influxdb
    adminUser:
      organization: homelab
      bucket: zepp
      user: admin
      retention_policy: "26280h"
      existingSecret: influxdb-auth
    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi
    service:
      type: ClusterIP
