apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          ports:
            - containerPort: 8080
          env:
            - name: INSTANCE_NAME
              value: open-webui-searxng
          volumeMounts:
            - name: settings
              mountPath: /etc/searxng
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: settings
          configMap:
            name: searxng-settings
